# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "vagrant-trac-extra"

  config.vm.synced_folder "../..", "/home/vagrant/repo/"

#  config.vm.network "forwarded_port", guest: 80, host: 8880
  config.vm.network "private_network", ip: "192.168.156.150"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

end

