# ansible-playbook -i prod install_webserver.yml --ask-sudo-pass -v
---
- name: Installation of trac-extra
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - role: webserver
      container_name: trac-extension
      image_name: g10k/trac-extension
      container_ports: 127.0.0.1:8083:8080
      conf_path: "/var/docker/{{ container_name }}/conf"
      data_path: "/var/docker/{{ container_name }}/data"
      log_path: "/var/docker/{{ container_name }}/log"
      static_path: "/var/www/{{ container_name }}/static"
      npm_path: "/var/www/{{ container_name }}/npm"
