# ansible-playbook -i staging -u root -v install_mis_mm_auth.yml -e "web_server_name=auth-stage.service.mm.consul logstash_server=logstash-stage.service.mm.consul"
# ansible-playbook -i prod -u root -v install_trac_extra.yml -e "web_server_name=trac.extra.com"

- name: Installation of microservice trac-extra
  hosts: all

  vars:
    container_name: trac-extension
    conf_path: "/var/docker/{{ container_name }}/conf"
    web_server_name: "188.166.23.131"

  roles:
    - role: djtrac
      image_name: g10k/trac-extension
      container_ports: 127.0.0.1:8091:8080
      data_path: "/var/docker/{{ container_name }}/data"
      log_path: "/var/docker/{{ container_name }}/log"
      static_path: "/var/www/{{ container_name }}/static"
      npm_path: "/var/www/{{ container_name }}/npm"
